# This file was generated by GoReleaser. DO NOT EDIT.
cask "meeting-transcriber" do
  name "meeting-transcriber"
  desc "On-device meeting audio transcription app powered by whisper.cpp"
  homepage "https://github.com/dannygim/meeting-transcriber"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meeting-transcriber"
  depends_on formula: [
      "portaudio",
      "whisper-cpp",
    ]

  on_macos do
    on_arm do
      url "https://github.com/dannygim/meeting-transcriber/releases/download/v#{version}/meeting-transcriber_#{version}_darwin_arm64.zip"
      sha256 "faa6ee7682209ffa3d3b06a7bd8831bad23e914873eeda7ea5f83ab359d3a557"
    end
  end

  caveats do
    "You need to download a Whisper model:"
    "  mkdir -p ~/models && curl -L -o ~/models/ggml-large-v3.bin \"
    "    https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin"
    ""
    "Since this app is unsigned, you may need to allow it in:"
    "  System Preferences > Security & Privacy"
  end

  uninstall quit: [
      "com.dannygim.meeting-transcriber",
    ]

  # No zap stanza required
end
