# This file was generated by GoReleaser. DO NOT EDIT.
cask "meeting-transcriber" do
  name "meeting-transcriber"
  desc "On-device meeting audio transcription app powered by whisper.cpp"
  homepage "https://github.com/dannygim/meeting-transcriber"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meeting-transcriber"
  depends_on formula: [
      "portaudio",
      "whisper-cpp",
    ]

  on_macos do
    on_arm do
      url "https://github.com/dannygim/meeting-transcriber/releases/download/v#{version}/meeting-transcriber_#{version}_darwin_arm64.zip"
      sha256 "1aa9a4a8e0c3eb151edb4daaec206d18b25c7c2b5cb17fc2c2e5e2cd7d916ebb"
    end
  end

  caveats do
    "You need to download a Whisper model:"
    "  mkdir -p ~/models && curl -Lo ~/models/ggml-large-v3.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin"
    ""
    "Since this app is unsigned, you may need to allow it in:"
    "  System Preferences > Security & Privacy"
  end

  uninstall quit: [
      "com.dannygim.meeting-transcriber",
    ]

  # No zap stanza required
end
