# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bgl < Formula
  desc "Backlog CLI - A command-line interface for Backlog"
  homepage "https://github.com/dannygim/bgl"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dannygim/bgl/releases/download/v0.1.1/bgl_0.1.1_darwin_amd64.tar.gz"
      sha256 "0fc0fd77a38703a27234d490cbc07274d1caa39f3674e44ecd4a4848b212efa7"

      def install
        bin.install "bgl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dannygim/bgl/releases/download/v0.1.1/bgl_0.1.1_darwin_arm64.tar.gz"
      sha256 "0423b744a67dfa38c76bf900e8ef3754d94daf76c37452356a71226b3461fe6b"

      def install
        bin.install "bgl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dannygim/bgl/releases/download/v0.1.1/bgl_0.1.1_linux_amd64.tar.gz"
      sha256 "715147403d9e8617b3642c4a00e0c0c477e63245276525a11ce848c56ba96750"
      def install
        bin.install "bgl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dannygim/bgl/releases/download/v0.1.1/bgl_0.1.1_linux_arm64.tar.gz"
      sha256 "0984cec7378c4e25868a46811aa15333f7d4ac7728e43c7017f75a37149596b0"
      def install
        bin.install "bgl"
      end
    end
  end

  test do
    system "#{bin}/bgl", "--help"
  end
end
