# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bgl < Formula
  desc "Backlog CLI - A command-line interface for Backlog"
  homepage "https://github.com/dannygim/bgl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dannygim/bgl/releases/download/v0.1.0/bgl_0.1.0_darwin_amd64.tar.gz"
      sha256 "ef63e3e4df9161272cedf4176a21e36ada6efd213d36073ea74336c84d4f3e47"

      def install
        bin.install "bgl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dannygim/bgl/releases/download/v0.1.0/bgl_0.1.0_darwin_arm64.tar.gz"
      sha256 "5387ee319be4c73923bd69e6613a95172e71f793b29e01329d1f26b54518f6ef"

      def install
        bin.install "bgl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dannygim/bgl/releases/download/v0.1.0/bgl_0.1.0_linux_amd64.tar.gz"
      sha256 "43df8245867da7045ebb648ca27ac088adea7e9f680f773b586fc4e7add8e6ed"
      def install
        bin.install "bgl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dannygim/bgl/releases/download/v0.1.0/bgl_0.1.0_linux_arm64.tar.gz"
      sha256 "81d1bc0a5d35e96b1bf371de16885466f5bb823eeaaed56ccaa1647ce8f6983a"
      def install
        bin.install "bgl"
      end
    end
  end

  test do
    system "#{bin}/bgl", "--help"
  end
end
