# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bgl < Formula
  desc "Backlog CLI - A command-line interface for Backlog"
  homepage "https://github.com/dannygim/bgl"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dannygim/bgl/releases/download/v0.3.0/bgl_0.3.0_darwin_amd64.tar.gz"
      sha256 "67df0b51fa22ab04a592792199ad66daaf85108e0266dd21d1ae0fce20afb3c4"

      define_method(:install) do
        bin.install "bgl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dannygim/bgl/releases/download/v0.3.0/bgl_0.3.0_darwin_arm64.tar.gz"
      sha256 "a0aba710520fb893ec409064148440215578e33698d5f5133356f1493899064d"

      define_method(:install) do
        bin.install "bgl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dannygim/bgl/releases/download/v0.3.0/bgl_0.3.0_linux_amd64.tar.gz"
      sha256 "df27143fc5c2dda24efeb909ef9ffa5f4c9df8523d9f1f8f57a5999e5a7eabf5"
      define_method(:install) do
        bin.install "bgl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dannygim/bgl/releases/download/v0.3.0/bgl_0.3.0_linux_arm64.tar.gz"
      sha256 "ca950469142048087ba8c292f9c0b95e2285bba3234216571643c3232f59d1e2"
      define_method(:install) do
        bin.install "bgl"
      end
    end
  end

  test do
    system "#{bin}/bgl", "--help"
  end
end
