# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MeetingTranscriber < Formula
  desc "On-device meeting audio transcription app powered by whisper.cpp"
  homepage "https://github.com/dannygim/meeting-transcriber"
  version "0.1.0"
  license "MIT"

  depends_on "portaudio"
  depends_on "whisper-cpp"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/dannygim/meeting-transcriber/releases/download/v0.1.0/meeting-transcriber_0.1.0_darwin_arm64.zip"
    sha256 "d39c8bacc87750a7a6d773636bd32abe56504f7196ab5ccd642a62679cbe0cc2"

    def install
      prefix.install "meeting-transcriber.app"
    end
  end

  def caveats
    <<~EOS
      You need to download a Whisper model:
        mkdir -p ~/models && curl -L -o ~/models/ggml-large-v3.bin \
          https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin

      Since this app is unsigned, you may need to allow it in:
        System Preferences > Security & Privacy
    EOS
  end

  test do
    assert_predicate prefix/"meeting-transcriber.app", :exist?
  end
end
